name: biznaga-cicd-demo
run-name: ${{ github.actor }} is testing out GitHub Actions

on: [push]
jobs:
  postman-test-job:
    runs-on: ubuntu-latest
    container:
      image: postman/newman:alpine
    steps:
    - name: Test 
      run: |
        echo "Checking NEWMAN version"
        newman --version
        echo "Installing reporter..."
        npm install -g newman-reporter-html
        echo "Running tests..."
        newman run "Rick&Morty.postman_collection.json" --reporters cli, html, junit --reporter-html-export report
    - name: Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: report
        path: report.html